DATABASE_USER: postgres
DATABASE_PASSWORD: password
DATABASE_HOST: 0.0.0.0
DATABASE_DATABASE: postgres
DATABASE_PORT: 5432
DATABASE_SSL: true
DATABASE_TIMEZONE: Europe/Amsterdam

SERVER_PORT: 8080
SERVER_ADDRESS: 0.0.0.0
SERVER_CORS: true

JWT_TOKEN: pcUsgsxc@691HgBHAinHwWn459TtaP@!)G(AALKJFowi$1$sf
